spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/ecrick
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      log-filter:
        pattern: (?mis)(?!.*(BATCH|last_insert_id).*)(.*)
      logging: custom
      custom-appender-class: com.ecrick.domain.config.CustomSlf4JLogger