version: '3'

services:
  db:
    image: mysql:8.1
    container_name: ecrick-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ecrick
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ~/db/mysql/ecrick/data:/var/lib/mysql
      - ~/db/mysql/ecrick/config:/etc/mysql/conf.d
      - ~/db/mysql/ecrick/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci