spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elib
    username: root
    password: 8989
  jpa:
    hibernate:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace    # ??? ???? ?? ???? ??? ? ??.

#server:
#  port : 8080