version: '3'

services:
#  nginx:
#    container_name: nginx
#    image: sandeulpark/my_nginx
#    platform: linux/amd64
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/lib/letsencrypt:/var/lib/letsencrypt
  green:
    container_name: green
    image: sandeulpark/elib:${APP_LATEST_TAG} # docker hub의 image 이름
    ports:
      - "8080:8080"  # green은 8080 포트를 열어줍니다.
    environment:
      SPRING_PROFILES_ACTIVE: prd
      OCI_DB_HOST: ${OCI_DB_HOST}
      OCI_DB_USERNAME: ${OCI_DB_USERNAME}
      OCI_DB_PASSWORD: ${OCI_DB_PASSWORD}
    restart: always
  blue:
    container_name: blue
    image: sandeulpark/elib:${APP_LATEST_TAG} # docker hub의 image 이름
    ports:
      - "8081:8080"  #blue는 8081 포트를 열어줍니다.
    profiles:
      - prd
    environment:
      SPRING_PROFILES_ACTIVE: prd
      OCI_DB_HOST: ${OCI_DB_HOST}
      OCI_DB_USERNAME: ${OCI_DB_USERNAME}
      OCI_DB_PASSWORD: ${OCI_DB_PASSWORD}