spring:
  profiles:
    active: dev
    group:
      dev:
        - db
  output.ansi.enabled: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${OCI_DB_HOST}
    username: ${OCI_DB_USERNAME}
    password: ${OCI_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}