spring:
  profiles.include: db
  jpa:
    open-in-view: false
    properties.hibernate.default_batch_fetch_size: 100
  datasource:
    url: jdbc:mariadb://${RDS.HOSTNAME}:${RDS.PORT}/${RDS.DB_NAME}
    username: ${RDS.USERNAME}
    password: ${RDS.PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver