spring:
  profiles:
    active: dev
    group:
      dev:
        - db
  output.ansi.enabled: always
  jpa:
    open-in-view: false
    properties.hibernate.default_batch_fetch_size: 100

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging.slack.webhook-url: ${SLACK_WEBHOOK_URL}