server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elib
    username: root
    password: 8989
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  devtools:
    livereload.enabled: true
    restart.enabled: true

logging.level.org.hibernate.SQL: debug