spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${OCI_DB_HOST}
    username: ${OCI_DB_USERNAME}
    password: ${OCI_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        max-page-size: 24