spring:
  output.ansi.enabled: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        dialect: com.ecrick.config.MariaDB106DialectCustom
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;

---

spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: ${OCI_DB_HOST}
    username: ${OCI_DB_USERNAME}
    password: ${OCI_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        max-page-size: 24