name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: elib

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#      #  소스코드 불러오기
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#
#      # 컨테이너 레지스트리 로그인
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      # 도커 이미지 빌드
#      - name: Buildpack make docker image
#        run: |
#          ./gradlew :server-service-server:bootBuildImage --imageName=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ github.run_number }}
#
#      # Docker Image push
#      - name: Publish Docker Image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ github.run_number }}

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_SSH_KEY }}
          port: 22
          script: pwd